// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// A professional sports conference (e.g., AFC, NFC)
type Conference struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Divisions []*Division `json:"divisions"`
}

// A division within a conference (e.g., AFC East, NFC West)
type Division struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Conference *Conference `json:"conference"`
	Teams      []*Team     `json:"teams"`
}

// Football-specific statistics
type FootballStats struct {
	PassingAttempts      int `json:"passingAttempts"`
	PassingCompletions   int `json:"passingCompletions"`
	PassingYards         int `json:"passingYards"`
	PassingTDs           int `json:"passingTDs"`
	PassingInterceptions int `json:"passingInterceptions"`
	RushingAttempts      int `json:"rushingAttempts"`
	RushingYards         int `json:"rushingYards"`
	RushingTDs           int `json:"rushingTDs"`
	ReceivingTargets     int `json:"receivingTargets"`
	ReceivingReceptions  int `json:"receivingReceptions"`
	ReceivingYards       int `json:"receivingYards"`
	ReceivingTDs         int `json:"receivingTDs"`
	Fumbles              int `json:"fumbles"`
	FumblesLost          int `json:"fumblesLost"`
	FieldGoals           int `json:"fieldGoals"`
	FieldGoalsMade       int `json:"fieldGoalsMade"`
	FieldGoalsMissed     int `json:"fieldGoalsMissed"`
	ExtraPoints          int `json:"extraPoints"`
	ExtraPointsMade      int `json:"extraPointsMade"`
	ExtraPointsMissed    int `json:"extraPointsMissed"`
}

// A professional player
type Player struct {
	ID                string        `json:"id"`
	FirstName         string        `json:"firstName"`
	LastName          string        `json:"lastName"`
	FullName          string        `json:"fullName"`
	Position          Position      `json:"position"`
	Team              *Team         `json:"team"`
	Height            *int          `json:"height,omitempty"`
	Weight            *int          `json:"weight,omitempty"`
	Age               *int          `json:"age,omitempty"`
	YearsOfExperience *int          `json:"yearsOfExperience,omitempty"`
	DraftYear         *int          `json:"draftYear,omitempty"`
	JerseyNumber      *int          `json:"jerseyNumber,omitempty"`
	Status            PlayerStatus  `json:"status"`
	Skill             *float64      `json:"skill,omitempty"`
	YearlyStats       []*YearlyStat `json:"yearlyStats"`
	TeamID            string        `json:"-"`
}

type Query struct {
}

// A professional sports team
type Team struct {
	ID           string    `json:"id"`
	City         string    `json:"city"`
	State        *string   `json:"state,omitempty"`
	Name         string    `json:"name"`
	Abbreviation string    `json:"abbreviation"`
	Division     *Division `json:"division"`
	Players      []*Player `json:"players"`
}

// Yearly statistics for a player
type YearlyStat struct {
	ID                   string         `json:"id"`
	Year                 int            `json:"year"`
	SportType            string         `json:"sportType"`
	Stats                *FootballStats `json:"stats,omitempty"`
	FantasyPoints        float64        `json:"fantasyPoints"`
	GamesPlayed          *int           `json:"gamesPlayed,omitempty"`
	FantasyPointsPerGame *float64       `json:"fantasyPointsPerGame,omitempty"`
}

type PlayerStatus string

const (
	PlayerStatusActive    PlayerStatus = "ACTIVE"
	PlayerStatusInjured   PlayerStatus = "INJURED"
	PlayerStatusPup       PlayerStatus = "PUP"
	PlayerStatusSuspended PlayerStatus = "SUSPENDED"
	PlayerStatusRetired   PlayerStatus = "RETIRED"
)

var AllPlayerStatus = []PlayerStatus{
	PlayerStatusActive,
	PlayerStatusInjured,
	PlayerStatusPup,
	PlayerStatusSuspended,
	PlayerStatusRetired,
}

func (e PlayerStatus) IsValid() bool {
	switch e {
	case PlayerStatusActive, PlayerStatusInjured, PlayerStatusPup, PlayerStatusSuspended, PlayerStatusRetired:
		return true
	}
	return false
}

func (e PlayerStatus) String() string {
	return string(e)
}

func (e *PlayerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerStatus", str)
	}
	return nil
}

func (e PlayerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Position string

const (
	PositionQb Position = "QB"
	PositionRb Position = "RB"
	PositionWr Position = "WR"
	PositionTe Position = "TE"
	PositionPk Position = "PK"
)

var AllPosition = []Position{
	PositionQb,
	PositionRb,
	PositionWr,
	PositionTe,
	PositionPk,
}

func (e Position) IsValid() bool {
	switch e {
	case PositionQb, PositionRb, PositionWr, PositionTe, PositionPk:
		return true
	}
	return false
}

func (e Position) String() string {
	return string(e)
}

func (e *Position) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Position(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Position", str)
	}
	return nil
}

func (e Position) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Position) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Position) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
