package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"

	"fantasy-draft/internal/db"

	"github.com/jackc/pgx/v5"
)

func main() {
	// 1. Get DB URL from environment (set in docker-compose)
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		log.Fatal("DATABASE_URL is not set")
	}

	// 2. Connect to the Database
	conn, err := pgx.Connect(context.Background(), dbURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(context.Background())
	fmt.Println("✅ Successfully connected to Postgres!")

	// 3. Initialize Queries (Generated by sqlc)
	// This "queries" object has methods like ListDraftRooms() attached to it.
	queries := db.New(conn)

	// 4. Register Routes
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Welcome to the Fantasy Draft API!")
	})

	http.HandleFunc("/rooms", func(w http.ResponseWriter, r *http.Request) {
		// A. Fetch data from DB
		// We pass "r.Context()" so if the user closes the tab, the DB query stops too.
		rooms, err := queries.ListDraftRooms(r.Context())
		if err != nil {
			http.Error(w, "Failed to fetch rooms", http.StatusInternalServerError)
			log.Printf("Error fetching rooms: %v", err)
			return
		}

		// B. Return JSON
		// Set the header so the browser knows it's JSON
		w.Header().Set("Content-Type", "application/json")
		// Marshal the struct into JSON and write it to the response
		if err := json.NewEncoder(w).Encode(rooms); err != nil {
			log.Printf("Error encoding response: %v", err)
		}
	})

	fmt.Println("🚀 Server starting on port 8080...")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}
