// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDraftRoom = `-- name: GetDraftRoom :one
SELECT id, status, created_at FROM draft_rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDraftRoom(ctx context.Context, id pgtype.UUID) (DraftRoom, error) {
	row := q.db.QueryRow(ctx, getDraftRoom, id)
	var i DraftRoom
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listDraftRooms = `-- name: ListDraftRooms :many
SELECT id, status, created_at FROM draft_rooms
ORDER BY created_at DESC
`

func (q *Queries) ListDraftRooms(ctx context.Context) ([]DraftRoom, error) {
	rows, err := q.db.Query(ctx, listDraftRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftRoom
	for rows.Next() {
		var i DraftRoom
		if err := rows.Scan(&i.ID, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
